### ISSUE TITLE
dark and mosaic theme issues

### ISSUE THREAD

**Issue by transgressor01** [Aluxian/Facebook-Messenger-Desktop#349]
no text is visible while writing; its too white to be seen in **Dark** and **Mosaic** themes, but in the default theme it is okay

**Comment by alexghi** [comment]
in the compiled css it looks like this selector is causing the issue: ```._4rv3```

**Comment by Marox44** [comment]
It started not a long time ago. **I checked it also on the linux version - same issue.**
Looks quite like that for me: 

![bug image](http://i.imgur.com/jGv3gSo.jpg)

**Comment by alexghi** [comment]
my guess is that maybe the css selector name has changed in messenger.com for some reasons and that's causing the issue, because basically the whole app resides in an iframe. 
I might be wrong though, is just a guessing.

**Comment by Sytten** [comment]
I will apply the PR on my fork this weekend.

**Comment by Marox44** [comment]
#345  ?

**Comment by bibbis** [comment]
Hi, has this issue been fixed?
I've had it for about a month now.

I don't understand much about what people are talking about in these posts.
Is this software open source and people are working on new versions together?

**Comment by Sytten** [comment]
@bibbis the software is indeed open source, if you check my fork (click on my profile you should see it) you will see that I corrected many bugs that the original apps have ;)

**Comment by bibbis** [comment]
@Sytten I don't know how to install that^^
do I need another program? gulp?
what is gulp?

**Comment by Sytten** [comment]
I will build it, so you will have a nice executable to install ;)

**Comment by bibbis** [comment]
@Sytten thank you, I appreciate that :)

**Comment by Sytten** [comment]
Done
https://sytten.github.io/Facebook-Messenger-Desktop/

**Comment by bibbis** [comment]
@Sytten thank you for this.
I really appreciate you taking the time :)

It's a really usefull app you people are working on here.

**Comment by Marox44** [comment]
@Sytten 
Yeah, it works really nice. Thanks a lot for working on it. :smiley: 
 It's great that someone is developing the app on his own, as unfortunatelly so far there are no new releases/bug fixes released by orgininal author(s) whatsoever :disappointed:

**Comment by Sytten** [comment]
Thank you, its a pleasure!
Their will be a completely new app soon he said based on Electron.
As soon as I have some time I will work on that new app.

**Comment by destinyshihn** [comment]
@Sytten Hello, sorry to bother you about this but while your dark theme fix for the messenger app works, it does not support the different color theme Facebook allows for chats, e.g if I set my chat color to say, purple, from my phone, it doens't show as such while using the dark theme, though it shows in both normal and mosaic theme. Is there a way to fix it?

**Comment by alexghi** [comment]
@destinyshihn Basically what you have to do is click on the i (information) button in the right top corner and there you have the option you're looking for.
You can also compile my fork which also supports dark theme, and chat color options.
You only need to compile it for your OS.
https://github.com/alexghi/Facebook-Messenger-Desktop

**Comment by destinyshihn** [comment]
@alexghi I know the option is here, when I use it the color still shows blue, that's what I meant, whereas when in normal and mosaic theme it shows the color I actually selected.

**Comment by Sytten** [comment]
Heeeee I will take a look maybe after my release. It should only be css tweaking...

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If the problem is still there, please open a new issue
